### ISSUE TITLE
I can't import pyfortune by "pip install py-fortune"

### ISSUE THREAD

**Issue by konishi0125** [mypaceshun/pyfortune#1]
![image](https://user-images.githubusercontent.com/31287152/60515537-c1562380-9d16-11e9-9a3b-5e1ba490a576.png)
place of installation to use "pip"
![image](https://user-images.githubusercontent.com/31287152/60515715-3590c700-9d17-11e9-8401-abb0c5b09cd8.png)
I can't import "pyfortune"
![image](https://user-images.githubusercontent.com/31287152/60516003-c7003900-9d17-11e9-8383-214d7bb6bac8.png)
or
![image](https://user-images.githubusercontent.com/31287152/60515942-a506b680-9d17-11e9-8527-18d43fee0018.png)
sys.path is
![image](https://user-images.githubusercontent.com/31287152/60515837-78eb3580-9d17-11e9-8d48-bb0025f8d067.png)
Would you solve this problem?

**Comment by mypaceshun** [comment]
This probrem is setup.py bug
Insufficient attributes for PyPI Metadata

**Comment by mypaceshun** [comment]
v0.9.4 で修正
